force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Date_Filed__c.field-meta.xml
<CustomField>
    <fullName>Date_Filed__c</fullName>
    <description>The date the claim was submitted.</description>
    <inlineHelpText>The date the claim was submitted.</inlineHelpText>
    <label>Date Filed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Days_Open__c.field-meta.xml
<CustomField>
    <fullName>Days_Open__c</fullName>
    <description>The number of days this claim has been open OR the number of days between the incident and the date filed. This field is automatically calculated.</description>
    <inlineHelpText>The number of days this claim has been open OR the number of days between the incident and the date filed. This field is automatically calculated.</inlineHelpText>
    <label>Days Open</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Incident_Date__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date__c</fullName>
    <description>The date the workplace incident occurred.</description>
    <inlineHelpText>The date the workplace incident occurred.</inlineHelpText>
    <label>Incident Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Is_High_Value__c.field-meta.xml
<CustomField>
    <fullName>Is_High_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This box will be checked if the Settlement Amount exceeds the company-defined threshold. This field is calculated automatically.</description>
    <inlineHelpText>This box will be checked if the Settlement Amount exceeds the company-defined threshold. This field is calculated automatically.</inlineHelpText>
    <label>Is High Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Amount__c</fullName>
    <description>The amount paid out on the claim.</description>
    <inlineHelpText>The amount paid out on the claim.</inlineHelpText>
    <label>Settlement Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Date__c</fullName>
    <description>The date this claim was settled. This field is calculated automatically.</description>
    <inlineHelpText>The date this claim was settled. This field is calculated automatically.</inlineHelpText>
    <label>Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current state of the claim.</description>
    <inlineHelpText>The current state of the claim.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaimTriggerHandler.cls
public class ClaimTriggerHandler {
    public static void updateClaimFields(
        // Pass in new/updated Claims (newClaims) and old/pre-update Claims (oldClaimsMap)
        // Pass in System.TriggerOperation operation type to dictate logic for before insert versus before update
        List<Claim__c> newClaims,
        Map<Id,Claim__c> oldClaimsMap,
        System.TriggerOperation operationType
    ) {
        // The company-defined dollar amount to classify a Claim as high value
        // Store this value in a variable to make it easy to update if business requirements change; this is preferable to hardcoding
        Decimal highValueSettlementAmount = 15000;

        if(operationType == System.TriggerOperation.BEFORE_INSERT || operationType == System.TriggerOperation.BEFORE_UPDATE) {
            for(Claim__c newClaim : newClaims) {
                // Confirm Incident Date is not in the future and Incident Date is not after Date Filed (you cannot file a report for an incident that hasn't occurred yet!)
                if(newClaim.Incident_Date__c <= Date.today() && newClaim.Incident_Date__c < newClaim.Date_Filed__c) {

                    // Check if Status field on Claim has been updated and also confirm the records that were updated exist (oldClaimsMap != null)
                    if(oldClaimsMap != null && oldClaimsMap.containsKey(newClaim.Id) && newClaim.Status__c != oldClaimsMap.get(newClaim.Id).Status__c) {

                        // If Claim is Settled and Settlement Amount > 0 and Settlement Date is blank, set Settlement Date to today
                        if(newClaim.Status__c == 'Settled' && newClaim.Settlement_Date__c == null && newClaim.Settlement_Amount__c > 0 && newClaim.Settlement_Amount__c != null) {
                            newClaim.Settlement_Date__c = Date.today();
                        }

                        // If Claim is Settled and Settlement Amount <= 0, display an error for user to correct Settlement Amount (a settled claim cannot have a zero or negative payout!)
                        else if(newClaim.Status__c == 'Settled' && newClaim.Settlement_Amount__c <= 0) {
                            newClaim.addError('Settlement Amount must be greater than zero before Claim is marked as Settled.');
                        }

                        // If Claim is Denied or in any other Status that is not Settled, and Settlement Amount != 0, set Settlement Amount to 0 (there is no payout if your claim is denied!)
                        else if((newClaim.Status__c == 'Denied' || newClaim.Status__c != 'Settled') && newClaim.Settlement_Amount__c != 0) {
                            newClaim.Settlement_Amount__c = 0;
                        }
                    }

                    // If Status field on Claim has not been updated and Status = Denied or Settled, then Days Open = Date Filed - Incident Date. If Status = Denied, then Settlement Amount = 0
                    else if(newClaim.Status__c == 'Denied' || newClaim.Status__c == 'Settled') {
                        newClaim.Days_Open__c = newClaim.Incident_Date__c.daysBetween(newClaim.Date_Filed__c);
                        if(newClaim.Status__c == 'Denied') {
                            newClaim.Settlement_Amount__c = 0;
                        }
                    }

                    // If Claim is still open and Status field has not been updated, Days Open = number of days between today and Incident Date
                    else if(newClaim.Status__c != 'Settled' && newClaim.Status__c != 'Denied') {
                        newClaim.Days_Open__c = newClaim.Incident_Date__c.daysBetween(Date.today());
                    }
                }

                // If the Incident Date is in the future OR after the Date Filed, display an error message informing the user of what is wrong
                else if(newClaim.Incident_Date__c > Date.today() || newClaim.Incident_Date__c > newClaim.Date_Filed__c) {
                    newClaim.addError('Incident Date must not be in the future. Incident Date cannot be later than Date Filed.');
                }

                // Check if Settlement Amount on Claim has been updated
                if(oldClaimsMap != null && newClaim.Settlement_Amount__c != oldClaimsMap.get(newClaim.Id).Settlement_Amount__c) {

                    // If Settlement Amount equals or exceeds the set threshold, set Is High Value to true
                    if(newClaim.Settlement_Amount__c >= highValueSettlementAmount) {
                        newClaim.Is_High_Value__c = true;
                    }

                    // If Settlement Amount is below the set threshold OR the Claim is Denied, set Is High Value to false
                    else if(newClaim.Settlement_Amount__c < highValueSettlementAmount || newClaim.Status__c == 'Denied') {
                        newClaim.Is_High_Value__c = false;
                    }
                }
            }
        }
    }
}