force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Insurance_Provider__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The insurance company handling this claim.</description>
    <inlineHelpText>The insurance company handling this claim.</inlineHelpText>
    <label>Insurance Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Amount__c</fullName>
    <description>The amount paid out on the claim.</description>
    <inlineHelpText>The amount paid out on the claim.</inlineHelpText>
    <label>Settlement Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <description>The employee&apos;s risk level. The value of this field is automatically set.</description>
    <inlineHelpText>The employee&apos;s risk level. The value of this field is automatically set.</inlineHelpText>
    <label>Risk Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Medium Risk</fullName>
            </value>
            <value>
                <fullName>High Risk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Total_Claims__c.field-meta.xml
<CustomField>
    <fullName>Total_Claims__c</fullName>
    <description>The total number of claims involving this employee. This field is calculated automatically.</description>
    <inlineHelpText>The total number of claims involving this employee. This field is calculated automatically.</inlineHelpText>
    <label>Total Claims</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Total_Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Settlement_Amount__c</fullName>
    <description>The sum of all settled claim payments associated with this employee. This field is automatically calculated.</description>
    <inlineHelpText>The sum of all settled claim payments associated with this employee. This field is automatically calculated.</inlineHelpText>
    <label>Total Settlement Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Claim__c/Employee_Claim__c.object-meta.xml
<CustomObject>
    <label>Employee Claim</label>
    <nameField>
        <label>Employee Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>The claim related to this employee.</description>
    <inlineHelpText>The claim related to this employee.</inlineHelpText>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employee_Claims1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Claim__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>The employee related to this claim.</description>
    <inlineHelpText>The employee related to this claim.</inlineHelpText>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Employee_Claims1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EmployeeClaimTriggerHandler.cls
public class EmployeeClaimTriggerHandler {
    public static void updateRiskLevel(
        // Pass in new/updated Employee Claims and old/deleted/undeleted Employee Claims
        // Pass in System.TriggerOperation operation type to dictate logic for insert/update versus delete/undelete
        List<Employee_Claim__c> newClaims,
        List<Employee_Claim__c> oldClaims,
        System.TriggerOperation operationType
    ) {
        // Risk thresholds - update as needed
        Decimal standard = 5000;
        Decimal medium = 10000;
        Decimal high = 20000;

        // Store the Employee Ids associated with new or old Employee Claims while avoiding duplicates
        Set<Id> employeeIds = new Set<Id>();

        // Populate the employeeIds set from the newClaims or oldClaims list depending on operation type
        System.debug('Operation Type: ' + operationType);
        if(operationType == System.TriggerOperation.AFTER_INSERT || operationType == System.TriggerOperation.AFTER_UPDATE) {
            for(Employee_Claim__c newClaim : newClaims) {
                employeeIds.add(newClaim.Employee__c);
            }
        }
        else if(operationType == System.TriggerOperation.AFTER_DELETE) {
            for(Employee_Claim__c oldClaim : oldClaims) {
                employeeIds.add(oldClaim.Employee__c);
            }
        }
        else if(operationType == System.TriggerOperation.AFTER_UNDELETE) {
            List<Employee_Claim__c> undeletedClaims = [SELECT Id, Employee__c FROM Employee_Claim__c WHERE Id IN :newClaims];
            for(Employee_Claim__c undeletedClaim : undeletedClaims) {
                employeeIds.add(undeletedClaim.Employee__c);
            }
        }
        System.debug('First block end');

        // This query returns all Employee Claims associated with employees whose Ids are in the employeeIds set, grouped by employee and provider, with the total amount per provider for each employee
        // Example: Oliver might have $500 in claims with Liberty Mutual and $100 in claims with Zurich
        List<AggregateResult> claimsByEmployeeAndProvider = [SELECT Employee__c, Claim__r.Insurance_Provider__c, SUM(Claim__r.Settlement_Amount__c) totalAmount FROM Employee_Claim__c WHERE Employee__c IN :employeeIds GROUP BY Employee__c, Claim__r.Insurance_Provider__c];

        Map<Id,Map<Id,Decimal>> employeeTotalByInsuranceProvider = new Map<Id,Map<Id,Decimal>>();
        // Loop through the AggregateResult list and populate the employeeTotalByInsuranceProvider map
        for(AggregateResult ar : claimsByEmployeeAndProvider) {
            Id employeeId = (Id)ar.get('Employee__c');
            Id providerId = (Id)ar.get('Insurance_Provider__c');
            Decimal totalAmount = (Decimal)ar.get('totalAmount');
            if(totalAmount == null) {
                totalAmount = 0;
            }
            if(!employeeTotalByInsuranceProvider.containsKey(employeeId)) {
                employeeTotalByInsuranceProvider.put(employeeId, new Map<Id,Decimal>{providerId => totalAmount});
            }
            else {
                employeeTotalByInsuranceProvider.get(employeeId).put(providerId, totalAmount);
            }
        }

        List<AggregateResult> totalClaimsAndAmountsByEmployee = [SELECT Employee__c, COUNT(Employee__r.Total_Claims__c) totalClaims, SUM(Employee__r.Total_Settlement_Amount__c) totalSettlementAmount FROM Employee_Claim__c WHERE Employee__c IN :employeeIds GROUP BY Employee__c];

        Map<Id,Integer> claimCounts = new Map<Id,Integer>();
        Map<Id,Decimal> settlementTotals = new Map<Id,Decimal>();

        for(AggregateResult ar : totalClaimsAndAmountsByEmployee) {
            Id employeeId = (Id)ar.get('Employee__c');
            Integer numberOfClaims = (Integer)ar.get('totalClaims');
            Decimal totalSettlementAmount = (Decimal)ar.get('totalSettlementAmount');
            if(!claimCounts.containsKey(employeeId)) {
                claimCounts.put(employeeId, numberOfClaims);
            }
            if(!settlementTotals.containsKey(employeeId)) {
                settlementTotals.put(employeeId, totalSettlementAmount);
            }
        }

        // Build a list of Employees based on the original employeeIds set to update Risk Levels
        // List<Employee__c> employeesWithRiskLevels = [SELECT Id, Risk_Level__c FROM Employee__c WHERE Id IN :employeeIds];

        // Build a list of Employees based on the original employeeIds set to update Risk Level, Total Claims, Total Settlement Amount
        List<Employee__c> employeesToUpdate = [SELECT Id, Risk_Level__c, Total_Claims__c, Total_Settlement_Amount__c FROM Employee__c WHERE Id IN :employeeIds];

        // Loop through the list of Employees
        for(Employee__c employee : employeesToUpdate) {
            // If the employee is in the employeeTotalByInsuranceProvider map, retrieve the inner map containing the employee's related providers and totals
            if(employeeTotalByInsuranceProvider.containsKey(employee.Id)) {
                // The providersAndTotals map will store the inner map<Id,Decimal> from the employeeTotalByInsuranceProvider map
                Map<Id,Decimal> providersAndTotals = employeeTotalByInsuranceProvider.get(employee.Id);
                // Extract the unduplicated provider Ids from the providersAndTotals map
                Set<Id> providerIds = providersAndTotals.keySet();
                if(!providerIds.isEmpty()) {
                    for(Id providerId : providerIds) {
                        Decimal totalAmount = providersAndTotals.get(providerId);
                        if(totalAmount > medium) {
                            employee.Risk_Level__c = 'High Risk';
                        }
                        else if(totalAmount > standard && totalAmount <= medium) {
                            employee.Risk_Level__c = 'Medium Risk';
                        }
                        else {
                            employee.Risk_Level__c = 'Standard';
                        }
                    }
                }
            }

            // If the employee is in the claimCounts map, update their Total Claims field using the map value
            if(claimCounts.containsKey(employee.Id)) {
                employee.Total_Claims__c = claimCounts.get(employee.Id);
            }

            // If the employee is in the settlementTotals map, update their Total Settlement Amount field using the map value
            if(settlementTotals.containsKey(employee.Id)) {
                employee.Total_Settlement_Amount__c = settlementTotals.get(employee.Id);
            }
        }

        System.debug('Updated risk level ran');
        // update employeesWithRiskLevels;
        update employeesToUpdate;
    } 
}