force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Insurance_Provider__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The insurance company handling this claim.</description>
    <inlineHelpText>The insurance company handling this claim.</inlineHelpText>
    <label>Insurance Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Amount__c</fullName>
    <description>The amount paid out on the claim.</description>
    <inlineHelpText>The amount paid out on the claim.</inlineHelpText>
    <label>Settlement Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <description>The employee&apos;s risk level. The value of this field is automatically set.</description>
    <inlineHelpText>The employee&apos;s risk level. The value of this field is automatically set.</inlineHelpText>
    <label>Risk Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Medium Risk</fullName>
            </value>
            <value>
                <fullName>High Risk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Total_Claims__c.field-meta.xml
<CustomField>
    <fullName>Total_Claims__c</fullName>
    <description>The total number of claims involving this employee. This field is calculated automatically.</description>
    <inlineHelpText>The total number of claims involving this employee. This field is calculated automatically.</inlineHelpText>
    <label>Total Claims</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Total_Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Settlement_Amount__c</fullName>
    <description>The sum of all settled claim payments associated with this employee. This field is automatically calculated.</description>
    <inlineHelpText>The sum of all settled claim payments associated with this employee. This field is automatically calculated.</inlineHelpText>
    <label>Total Settlement Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Claim__c/Employee_Claim__c.object-meta.xml
<CustomObject>
    <label>Employee Claim</label>
    <nameField>
        <label>Employee Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>The claim related to this employee.</description>
    <inlineHelpText>The claim related to this employee.</inlineHelpText>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employee_Claims1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Claim__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>The employee related to this claim.</description>
    <inlineHelpText>The employee related to this claim.</inlineHelpText>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Employee_Claims1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EmployeeClaimTriggerHandlerTest.cls
@isTest
private class EmployeeClaimTriggerHandlerTest {
    public static List<Employee_Claim__c> employeeClaims = new List<Employee_Claim__c>();
    public static List<Claim__c> testClaimsList = new List<Claim__c>();
    
    @TestSetup
    static void createTestData(){

        // Create test Accounts to represent Insurance Providers
        List<Account> testProvidersList = new List<Account>();

        for(Integer i = 0; i < 10; i++) {
            Account testProvider = new Account();
            testProvider.Name = 'Test Provider ' + i;
            testProvidersList.add(testProvider);
        }

        insert testProvidersList;

        Integer providerCounter = 0;
        Integer providerMaxCounter = 10;

        // Create test Employees
        List<Employee__c> testEmployeesList = new List<Employee__c>();

        for(Integer i = 0; i < 50; i++) {
            Employee__c testEmployee = new Employee__c();
            testEmployee.Name = 'Test Person ' + i;
            testEmployeesList.add(testEmployee);
        }

        insert testEmployeesList;

        Integer employeeCounter = 0;
        Integer employeeMaxCounter = 50;

        // Create test Claims
        for(Integer i = 0; i < 100; i++) {
            Claim__c testClaim = new Claim__c();
            testClaim.Name = 'My Test Claim ' + i;
            testClaim.Settlement_Amount__c = 2000;
            if(providerCounter < providerMaxCounter) {
                testClaim.Insurance_Provider__c = testProvidersList.get(providerCounter).Id;
                providerCounter++;
            }
            if(providerCounter == providerMaxCounter) {
                providerCounter = 0;
            }
            testClaimsList.add(testClaim);
        }

        insert testClaimsList;

        Integer claimCounter = 0;
        Integer claimMaxCounter = 100;

        // Create test Employee Claims
        for(Integer i = 0; i < 200; i++) {
            Employee_Claim__c testEmployeeClaim = new Employee_Claim__c();
            testEmployeeClaim.Name = 'My Test EC ' + i;
            if(employeeCounter < employeeMaxCounter) {
                testEmployeeClaim.Employee__c = testEmployeesList.get(employeeCounter).Id;
                employeeCounter++;
            }
            if(employeeCounter == employeeMaxCounter) {
                employeeCounter = 0;
            }
            if(claimCounter < claimMaxCounter) {
                testEmployeeClaim.Claim__c = testClaimsList.get(claimCounter).Id;
                claimCounter++;
            }
            if(claimCounter == claimMaxCounter) {
                claimCounter = 0;
            }
            employeeClaims.add(testEmployeeClaim);
        }

        insert employeeClaims;
    }

    @isTest
    static void testEmployeeClaimTriggerHandler_updateRiskLevelOnInsert() {
        List<Employee_Claim__c> newClaims = [SELECT Id, Employee__c, Claim__r.Insurance_Provider__c, Claim__r.Settlement_Amount__c FROM Employee_Claim__c WHERE NAME LIKE '%Test%'];
        List<Employee_Claim__c> oldClaims = new List<Employee_Claim__c>();

        Test.startTest();
        EmployeeClaimTriggerHandler.updateRiskLevel(newClaims, oldClaims, System.TriggerOperation.AFTER_INSERT);
        Test.stopTest();

        Set<Id> employeeIds = new Set<Id>();
        
        List<Employee_Claim__c> updatedClaims = [SELECT Id, Employee__c, Claim__r.Insurance_Provider__c, Claim__r.Settlement_Amount__c, Employee__r.Total_Claims__c, Employee__r.Total_Settlement_Amount__c FROM Employee_Claim__c WHERE Id IN :newClaims];
        for(Employee_Claim__c updatedClaim : updatedClaims) {
            employeeIds.add(updatedClaim.Employee__c);
        }

        List<Employee__c> updatedEmployees = [SELECT Id, Risk_Level__c FROM Employee__c WHERE Id IN :employeeIds];
        for(Employee__c updatedEmployee : updatedEmployees) {
            Assert.areEqual('Standard', updatedEmployee.Risk_Level__c);
        }
    }

    /*
    @isTest
    static void testEmployeeClaimTriggerHandler_updateRiskLevelOnUpdate() {

        for(Claim__c claim : testClaimsList) {
            claim.Settlement_Amount__c = 15000;
        }

        update testClaimsList;

        List<Employee_Claim__c> newClaims = [SELECT Id, Employee__c, Claim__r.Insurance_Provider__c, Claim__r.Settlement_Amount__c FROM Employee_Claim__c WHERE NAME LIKE '%Test%'];
        List<Employee_Claim__c> oldClaims = [SELECT Id, Employee__c, Claim__r.Insurance_Provider__c, Claim__r.Settlement_Amount__c FROM Employee_Claim__c WHERE NAME LIKE '%Test%'];

        update newClaims;

        Test.startTest();
        EmployeeClaimTriggerHandler.updateRiskLevel(newClaims, oldClaims, System.TriggerOperation.AFTER_UPDATE);
        Test.stopTest();

        Set<Id> employeeIds = new Set<Id>();
        
        List<Employee_Claim__c> updatedClaims = [SELECT Id, Employee__c, Claim__r.Insurance_Provider__c, Claim__r.Settlement_Amount__c, Employee__r.Total_Claims__c, Employee__r.Total_Settlement_Amount__c FROM Employee_Claim__c WHERE Id IN :newClaims];
        for(Employee_Claim__c updatedClaim : updatedClaims) {
            employeeIds.add(updatedClaim.Employee__c);
        }

        List<Employee__c> updatedEmployees = [SELECT Id, Risk_Level__c FROM Employee__c WHERE Id IN :employeeIds];
        for(Employee__c updatedEmployee : updatedEmployees) {
            Assert.areEqual('Medium Risk', updatedEmployee.Risk_Level__c);
        }
    }
    */
}